FROM python:3.11-slim

WORKDIR /app



RUN pip install uv 

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY . .

WORKDIR /app/core

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

EXPOSE 8000

ENTRYPOINT [ "/entrypoint.sh" ]