# Generated by Django 5.2.6 on 2025-09-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="imageUrl",
            field=models.CharField(max_length=200),
        ),
    ]
