# Generated by Django 5.2.6 on 2026-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bavoirs', 'Bavoirs'), ('doudous', 'Doudous'), ('couvertures', 'Couvertures')], default='bavoirs', max_length=50),
        ),
    ]
