# Generated by Django 5.2.6 on 2026-01-08 15:56

from django.db import migrations, models

def create_default_settings(apps, schema_editor):
    SiteSettings = apps.get_model('api', 'SiteSettings')
    SiteSettings.objects.create(orders_enabled=False)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.RunPython(create_default_settings),
    ]
